### ISSUE TITLE
Administrator Permissions

### ISSUE THREAD

**Issue by fairycn** [DarkCoderSc/PsyloDbg#2]
If the debugged program requires administrator privileges, you need to run PsyloDbg with administrator privileges when you start it. 
Otherwise, no information will be displayed

**Comment by DarkCoderSc** [comment]
Hello,

Just to be sure

You mean that if program to debug requires administrator privilege and psylo does not run as admin nothing happens ?

A fix would be to display a warning / error message to tell user to run psylo as administrator in order to debug target app , right ?

Regards

**Comment by DarkCoderSc** [comment]
Issue fixed for next release ;) 

Thank you!
